### PR TITLE
Pad lines in PDB files which are too short

### PR DESCRIPTION
**Pull request by ncoish**
A malformed PDB file may be missing whitespace on the end of some lines. This change pads those lines in hopes that the file can be parsed properly.
An equivalent change was made to Biotite several months ago in [this commit](https://github.com/biotite-dev/biotite/commit/41dab12b33456497bbc1801e186d2e24732cae00), so this is copying the behaviour.

Additionally, I noticed this problem because when fastpdb itself writes CRYST1 records, it writes the lines as only 70 characters instead of 80. I took the liberty of fixing this as well. However, I believe that Biotite also has this same CRYST1 writing error. So if this commit is merged, the behaviour of biotite and fastpdb will change very slightly unless a fix is also made in Biotite.

### CODE REVIEW

**Comment by ncoish** [comment]
I think the tests are failing for the reason that I pointed out in the description, since the behaviour differs slightly in whitespace from the current version of biotite. Should I remove that commit here until biotite adopts a similar change (if it will adopt a similar change)?

**Comment by padix-key** [comment]
Thank you for the fix. Please also keep the commit regarding the `CRYST1` record in this PR, I will create a fix for this in Biotite accordingly.

**Comment by padix-key** [comment]
I ran the tests using my Biotite buildwith fixed `CRYST1` record. Indeed all tests pass without errors in this case. Hence I will merge this PR.

**Comment by ncoish** [comment]
> I ran the tests using my Biotite buildwith fixed `CRYST1` record. Indeed all tests pass without errors in this case. Hence I will merge this PR.

Fantastic! I'm not sure if you have a timeline yet, but when do you anticipate publishing the next versions of `biotite`/`fastpdb`?

**Comment by padix-key** [comment]
Currently a new CD pipeline for Biotite is under review (https://github.com/biotite-dev/biotite/pull/451). I will publish a new version when this PR is merged, adding support for Python 3.11. This will probably happen in two weeks.

For the next `fastpdb` release I would like to have issue #1 resolved. This will hopefully be the case shortly after the Biotite release.

**Comment by padix-key** [comment]
One last thing I just recognized: Is there a reason for removing the test for bad PDB files, or did this happen by accident?

**Comment by ncoish** [comment]
> One last thing I just recognized: Is there a reason for removing the test for bad PDB files, or did this happen by accident?

I added that test during the previous PR related to raising exceptions, but it turns out that the behaviour was being triggered by a different mechanism than I originally thought (in fact, it's the mechanism we're fixing here :stuck_out_tongue:). So that test no longer functions as expected.

I thought the failure was being triggered originally because the files were missing their `element` column, but it was actually just happening because the lines were not 80 characters long.

**Pull request merged**
